# Generated by Django 2.2.13 on 2021-02-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210225_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'verbose_name': 'Запись в телефонной книге', 'verbose_name_plural': 'Записи в телефонной книге'},
        ),
    ]
