# Generated by Django 2.2.13 on 2021-02-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20210225_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='phone_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='phonebook.PhoneBook', verbose_name='Чей номер'),
        ),
    ]
