# Generated by Django 2.2.13 on 2021-02-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_auto_20210226_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='category',
        ),
    ]
