# Generated by Django 2.2.13 on 2021-02-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0007_remove_numbers_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='categorys',
        ),
        migrations.AddField(
            model_name='numbers',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='numbers', to='phonebook.Category'),
        ),
    ]
