# Generated by Django 2.2.13 on 2021-02-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_auto_20210226_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='category',
        ),
        migrations.AddField(
            model_name='numbers',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='numbers', to='phonebook.Category', verbose_name='Категория'),
        ),
    ]
