# Generated by Django 2.2.13 on 2021-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0011_auto_20210226_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'verbose_name': 'Запись в телефонном справочнике', 'verbose_name_plural': 'Записи в телефонном справочнике'},
        ),
    ]
