# Generated by Django 2.2.13 on 2021-02-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0012_auto_20210226_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='phonebook.Category', verbose_name='Категория'),
        ),
    ]
