# Generated by Django 2.2.13 on 2021-02-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0013_auto_20210226_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.CharField(max_length=25, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='phone_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='phonebook.PhoneBook', verbose_name='Чей номер'),
        ),
    ]
