# Generated by Django 2.2.13 on 2021-02-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0014_auto_20210226_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='avatar',
        ),
    ]
